stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - if exist public rmdir /s /q public
    - mkdir public
    - xcopy /E /I /Y dist public
  artifacts:
    paths:
      - public
  only:
    - master
    - main
